### ISSUE TITLE
Hex file contains invalid record at line 1 while flashing using Serial Boot Loader (SBL)

### ISSUE THREAD

**Issue by akrv** [akrv/sensorfloor#2]
error while flashing a committed hex file in addr_finder.

```
Opening port /dev/ttyUSB0, baud 500000
Reading data from ../addr_finder/hex_15_file/address_finder_1.simplelink.hex
Your firmware looks like an Intel Hex file
ERROR: Hex file contains invalid record at line 1
```

already installed dependencies  
`pip install intelhex`

and trying to flash imu_app give this output

```
Target returned: 0x43, Invalid address
^CTraceback (most recent call last):
  File "cc2538-bsl.py", line 1197, in <module>

```

why is it not working?

**Comment by AnasIbrahim** [comment]
I updated the hex files in imu app (sensorfloor/imu_app/imu_ti_workspace/imu_data_interrupt/Release/imu_data_interrupt.hex) and addr_finder (sensorfloor/addr_finder/hex_15_file/***).

**Comment by akrv** [comment]
same error with this firmware as well.
jelmer cc2538-bsl.py -h printout this example line.

`./cc2538-bsl.py -e -w -v example/main.bin`

can we get .bin files?

**Comment by AnasIbrahim** [comment]
I committed the .bin file with bootloader enabled [sensorfloor/imu_app/imu_ti_workspace/imu_data_interrupt/Release/imu_data_interrupt.bin]. Please test it and tell me if the bootloader was correctly enabled.
